# Generated by Django 5.0.4 on 2024-04-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=30)),
                ('sender_email', models.EmailField(max_length=30)),
                ('content', models.TextField()),
                ('sent_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
