# Generated by Django 5.0.4 on 2024-04-27 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_messages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageReceived',
            new_name='Message',
        ),
    ]
