# Generated by Django 5.0.4 on 2024-04-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('Lang', 'Language'), ('Tech', 'Technology')], default='Lang', max_length=20)),
                ('image', models.ImageField(upload_to='media_to_migrate')),
            ],
        ),
    ]
